[build]
builder = "nixpacks"

[build.nixpacks]
install = "npm install"
build = "npm run build"
start = "npx serve -s build -l $PORT"

[deploy]
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
